Add powershell script for windows wasm build

diff --git a/ci/steps.yml b/ci/steps.yml
--- a/ci/steps.yml
+++ b/ci/steps.yml
@@ -339,5 +339,51 @@ steps:
       qmake $(Build.BinariesDirectory)/tests/openglwindow
       make
     workingDirectory: $(Build.BinariesDirectory)
-    condition: and(eq( variables['ARCH'], 'wasm_32' ), or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin')))
-    displayName: 'Build WebAssembler sample project'
+    condition: |
+      and(
+        eq( variables['ARCH'], 'wasm_32' ),
+        or(
+          eq(variables['Agent.OS'], 'Linux'),
+          eq(variables['Agent.OS'], 'Darwin')
+        )
+      )
+    displayName: 'Build WebAssembler sample project on mac/linux'
+
+  # wasm_32 on Windows cmd.exe
+  - powershell: |
+      git clone https://github.com/emscripten-core/emsdk.git
+      cd emsdk
+      .\emsdk install sdk-fastcomp-1.38.27-64bit
+      .\emsdk activate --embedded  sdk-fastcomp-1.38.27-64bit
+      .\emsdk_env.bat
+      mkdir $(Build.BinariesDirectory)\tests
+      cd $(Build.BinariesDirectory)\tests
+      7z x $(Build.SourcesDirectory)\ci\openglwindow.7z
+      $env:Path += ";$(WIN_QT_BINDIR)"
+      echo "Add Qt/qmake to PATH at $(WIN_QT_BINDIR):" 
+      echo "$env:Path"
+      if('$(QT_VERSION)' -like '6*') {
+        echo "Qt6: run qmake.bat"
+        qmake.bat $(Build.BinariesDirectory)\tests\openglwindow
+      } else {
+        echo "Qt5: run qmake.exe"
+        qmake $(Build.BinariesDirectory)\tests\openglwindow
+      }
+      if ($false -eq $?) {
+        Write-Error "qmake failed."
+        Write-Host "##vso[task.logissue type=error]qmake failed."
+        exit(1)
+      }
+      make
+      if ($false -eq $?) {
+        Write-Error "make failed."
+        Write-Host "##vso[task.logissue type=error]nmake failed."
+        exit(1)
+      }
+    workingDirectory: $(Build.BinariesDirectory)
+    condition: |
+      and(
+        eq( variables['ARCH'], 'wasm_32' ),
+        eq( variables['Agent.OS'], 'Windows_NT' )
+      )
+    displayName: 'Build WebAssembler sample project on windows'
